package InterfaceGrafica;

import Entidades.Carta;
import Entidades.Jogador;
import Entidades.Tabuleiro;
import java.util.ArrayList;
import javax.swing.Icon;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.

import javax.swing.Icon;
import javax.swing.JButton;

/**
 *
 * @author Carol
 */
public class InterfaceTabuleiro extends javax.swing.JPanel {

    Icon casaverde = new javax.swing.ImageIcon(getClass().getResource("verde.png"));
    Icon casavermelho = new javax.swing.ImageIcon(getClass().getResource("vermelho.png"));
    ArrayList<javax.swing.JLabel> espacoCartas;
    /**
     * Creates new form NewJPanel
     */
    public InterfaceTabuleiro() {
        initComponents();
        iniciarTabuleiro(1);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        casa1 = new javax.swing.JButton();
        casa2 = new javax.swing.JButton();
        casa3 = new javax.swing.JButton();
        casa4 = new javax.swing.JButton();
        casa5 = new javax.swing.JButton();
        casa6 = new javax.swing.JButton();
        casa7 = new javax.swing.JButton();
        casa8 = new javax.swing.JButton();
        casa9 = new javax.swing.JButton();
        casa10 = new javax.swing.JButton();
        casa11 = new javax.swing.JButton();
        casa12 = new javax.swing.JButton();
        casa13 = new javax.swing.JButton();
        casa14 = new javax.swing.JButton();
        casa15 = new javax.swing.JButton();
        casa16 = new javax.swing.JButton();
        casa17 = new javax.swing.JButton();
        casa18 = new javax.swing.JButton();
        casa19 = new javax.swing.JButton();
        casa20 = new javax.swing.JButton();
        casa21 = new javax.swing.JButton();
        casa22 = new javax.swing.JButton();
        casa23 = new javax.swing.JButton();
        casa24 = new javax.swing.JButton();
        casa25 = new javax.swing.JButton();
        casa26 = new javax.swing.JButton();
        casa27 = new javax.swing.JButton();
        casa28 = new javax.swing.JButton();
        casa29 = new javax.swing.JButton();
        casa30 = new javax.swing.JButton();
        casa31 = new javax.swing.JButton();
        casa32 = new javax.swing.JButton();
        fverde1 = new javax.swing.JButton();
        fverde2 = new javax.swing.JButton();
        fverde3 = new javax.swing.JButton();
        fverde4 = new javax.swing.JButton();
        fvermelho1 = new javax.swing.JButton();
        fvermelho2 = new javax.swing.JButton();
        fvermelho3 = new javax.swing.JButton();
        fvermelho4 = new javax.swing.JButton();
        cvermelho1 = new javax.swing.JButton();
        cvermelho2 = new javax.swing.JButton();
        cvermelho3 = new javax.swing.JButton();
        cvermelho4 = new javax.swing.JButton();
        cverde1 = new javax.swing.JButton();
        cverde2 = new javax.swing.JButton();
        cverde3 = new javax.swing.JButton();
        cverde4 = new javax.swing.JButton();
        carta1 = new javax.swing.JLabel();
        carta2 = new javax.swing.JLabel();
        carta3 = new javax.swing.JLabel();
        carta4 = new javax.swing.JLabel();
        carta5 = new javax.swing.JLabel();
        carta6 = new javax.swing.JLabel();
        descarte = new javax.swing.JLabel();

        setBackground(new java.awt.Color(185, 122, 87));

        casa1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/InterfaceGrafica/vazio.png"))); // NOI18N
        casa1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 153, 0), 3));
        casa1.setPreferredSize(new java.awt.Dimension(50, 50));
        casa1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                casa1ActionPerformed(evt);
            }
        });

        casa2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/InterfaceGrafica/vazio.png"))); // NOI18N
        casa2.setPreferredSize(new java.awt.Dimension(50, 50));
        casa2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                casa2ActionPerformed(evt);
            }
        });

        casa3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/InterfaceGrafica/vazio.png"))); // NOI18N
        casa3.setPreferredSize(new java.awt.Dimension(50, 50));
        casa3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                casa3ActionPerformed(evt);
            }
        });

        casa4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/InterfaceGrafica/vazio.png"))); // NOI18N
        casa4.setPreferredSize(new java.awt.Dimension(50, 50));
        casa4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                casa4ActionPerformed(evt);
            }
        });

        casa5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/InterfaceGrafica/vazio.png"))); // NOI18N
        casa5.setPreferredSize(new java.awt.Dimension(50, 50));
        casa5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                casa5ActionPerformed(evt);
            }
        });

        casa6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/InterfaceGrafica/vazio.png"))); // NOI18N
        casa6.setPreferredSize(new java.awt.Dimension(50, 50));
        casa6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                casa6ActionPerformed(evt);
            }
        });

        casa7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/InterfaceGrafica/vazio.png"))); // NOI18N
        casa7.setPreferredSize(new java.awt.Dimension(50, 50));
        casa7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                casa7ActionPerformed(evt);
            }
        });

        casa8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/InterfaceGrafica/vazio.png"))); // NOI18N
        casa8.setPreferredSize(new java.awt.Dimension(50, 50));
        casa8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                casa8ActionPerformed(evt);
            }
        });

        casa9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/InterfaceGrafica/vazio.png"))); // NOI18N
        casa9.setPreferredSize(new java.awt.Dimension(50, 50));
        casa9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                casa9ActionPerformed(evt);
            }
        });

        casa10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/InterfaceGrafica/vazio.png"))); // NOI18N
        casa10.setPreferredSize(new java.awt.Dimension(50, 50));
        casa10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                casa10ActionPerformed(evt);
            }
        });

        casa11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/InterfaceGrafica/vazio.png"))); // NOI18N
        casa11.setPreferredSize(new java.awt.Dimension(50, 50));
        casa11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                casa11ActionPerformed(evt);
            }
        });

        casa12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/InterfaceGrafica/vazio.png"))); // NOI18N
        casa12.setPreferredSize(new java.awt.Dimension(50, 50));
        casa12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                casa12ActionPerformed(evt);
            }
        });

        casa13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/InterfaceGrafica/vazio.png"))); // NOI18N
        casa13.setPreferredSize(new java.awt.Dimension(50, 50));
        casa13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                casa13ActionPerformed(evt);
            }
        });

        casa14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/InterfaceGrafica/vazio.png"))); // NOI18N
        casa14.setPreferredSize(new java.awt.Dimension(50, 50));
        casa14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                casa14ActionPerformed(evt);
            }
        });

        casa15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/InterfaceGrafica/vazio.png"))); // NOI18N
        casa15.setPreferredSize(new java.awt.Dimension(50, 50));
        casa15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                casa15ActionPerformed(evt);
            }
        });

        casa16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/InterfaceGrafica/vazio.png"))); // NOI18N
        casa16.setPreferredSize(new java.awt.Dimension(50, 50));
        casa16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                casa16ActionPerformed(evt);
            }
        });

        casa17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/InterfaceGrafica/vazio.png"))); // NOI18N
        casa17.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 0, 0), 3));
        casa17.setPreferredSize(new java.awt.Dimension(50, 50));
        casa17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                casa17ActionPerformed(evt);
            }
        });

        casa18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/InterfaceGrafica/vazio.png"))); // NOI18N
        casa18.setPreferredSize(new java.awt.Dimension(50, 50));
        casa18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                casa18ActionPerformed(evt);
            }
        });

        casa19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/InterfaceGrafica/vazio.png"))); // NOI18N
        casa19.setPreferredSize(new java.awt.Dimension(50, 50));
        casa19.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                casa19ActionPerformed(evt);
            }
        });

        casa20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/InterfaceGrafica/vazio.png"))); // NOI18N
        casa20.setPreferredSize(new java.awt.Dimension(50, 50));
        casa20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                casa20ActionPerformed(evt);
            }
        });

        casa21.setIcon(new javax.swing.ImageIcon(getClass().getResource("/InterfaceGrafica/vazio.png"))); // NOI18N
        casa21.setPreferredSize(new java.awt.Dimension(50, 50));
        casa21.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                casa21ActionPerformed(evt);
            }
        });

        casa22.setIcon(new javax.swing.ImageIcon(getClass().getResource("/InterfaceGrafica/vazio.png"))); // NOI18N
        casa22.setPreferredSize(new java.awt.Dimension(50, 50));
        casa22.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                casa22ActionPerformed(evt);
            }
        });

        casa23.setIcon(new javax.swing.ImageIcon(getClass().getResource("/InterfaceGrafica/vazio.png"))); // NOI18N
        casa23.setPreferredSize(new java.awt.Dimension(50, 50));
        casa23.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                casa23ActionPerformed(evt);
            }
        });

        casa24.setIcon(new javax.swing.ImageIcon(getClass().getResource("/InterfaceGrafica/vazio.png"))); // NOI18N
        casa24.setPreferredSize(new java.awt.Dimension(50, 50));
        casa24.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                casa24ActionPerformed(evt);
            }
        });

        casa25.setIcon(new javax.swing.ImageIcon(getClass().getResource("/InterfaceGrafica/vazio.png"))); // NOI18N
        casa25.setPreferredSize(new java.awt.Dimension(50, 50));
        casa25.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                casa25ActionPerformed(evt);
            }
        });

        casa26.setIcon(new javax.swing.ImageIcon(getClass().getResource("/InterfaceGrafica/vazio.png"))); // NOI18N
        casa26.setPreferredSize(new java.awt.Dimension(50, 50));
        casa26.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                casa26ActionPerformed(evt);
            }
        });

        casa27.setIcon(new javax.swing.ImageIcon(getClass().getResource("/InterfaceGrafica/vazio.png"))); // NOI18N
        casa27.setPreferredSize(new java.awt.Dimension(50, 50));
        casa27.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                casa27ActionPerformed(evt);
            }
        });

        casa28.setIcon(new javax.swing.ImageIcon(getClass().getResource("/InterfaceGrafica/vazio.png"))); // NOI18N
        casa28.setPreferredSize(new java.awt.Dimension(50, 50));
        casa28.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                casa28ActionPerformed(evt);
            }
        });

        casa29.setIcon(new javax.swing.ImageIcon(getClass().getResource("/InterfaceGrafica/vazio.png"))); // NOI18N
        casa29.setPreferredSize(new java.awt.Dimension(50, 50));
        casa29.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                casa29ActionPerformed(evt);
            }
        });

        casa30.setIcon(new javax.swing.ImageIcon(getClass().getResource("/InterfaceGrafica/vazio.png"))); // NOI18N
        casa30.setPreferredSize(new java.awt.Dimension(50, 50));
        casa30.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                casa30ActionPerformed(evt);
            }
        });

        casa31.setIcon(new javax.swing.ImageIcon(getClass().getResource("/InterfaceGrafica/vazio.png"))); // NOI18N
        casa31.setPreferredSize(new java.awt.Dimension(50, 50));
        casa31.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                casa31ActionPerformed(evt);
            }
        });

        casa32.setIcon(new javax.swing.ImageIcon(getClass().getResource("/InterfaceGrafica/vazio.png"))); // NOI18N
        casa32.setPreferredSize(new java.awt.Dimension(50, 50));
        casa32.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                casa32ActionPerformed(evt);
            }
        });

        fverde1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/InterfaceGrafica/vazio.png"))); // NOI18N
        fverde1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 153, 51), 3, true));
        fverde1.setPreferredSize(new java.awt.Dimension(50, 50));
        fverde1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fverde1ActionPerformed(evt);
            }
        });

        fverde2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/InterfaceGrafica/vazio.png"))); // NOI18N
        fverde2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 153, 51), 3, true));
        fverde2.setPreferredSize(new java.awt.Dimension(50, 50));
        fverde2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fverde2ActionPerformed(evt);
            }
        });

        fverde3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/InterfaceGrafica/vazio.png"))); // NOI18N
        fverde3.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 153, 51), 3, true));
        fverde3.setPreferredSize(new java.awt.Dimension(50, 50));
        fverde3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fverde3ActionPerformed(evt);
            }
        });

        fverde4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/InterfaceGrafica/vazio.png"))); // NOI18N
        fverde4.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 153, 51), 3, true));
        fverde4.setPreferredSize(new java.awt.Dimension(50, 50));
        fverde4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fverde4ActionPerformed(evt);
            }
        });

        fvermelho1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/InterfaceGrafica/vazio.png"))); // NOI18N
        fvermelho1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 0, 0), 3, true));
        fvermelho1.setPreferredSize(new java.awt.Dimension(50, 50));
        fvermelho1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fvermelho1ActionPerformed(evt);
            }
        });

        fvermelho2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/InterfaceGrafica/vazio.png"))); // NOI18N
        fvermelho2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 0, 0), 3, true));
        fvermelho2.setPreferredSize(new java.awt.Dimension(50, 50));
        fvermelho2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fvermelho2ActionPerformed(evt);
            }
        });

        fvermelho3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/InterfaceGrafica/vazio.png"))); // NOI18N
        fvermelho3.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 0, 0), 3, true));
        fvermelho3.setPreferredSize(new java.awt.Dimension(50, 50));
        fvermelho3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fvermelho3ActionPerformed(evt);
            }
        });

        fvermelho4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/InterfaceGrafica/vazio.png"))); // NOI18N
        fvermelho4.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 0, 0), 3, true));
        fvermelho4.setPreferredSize(new java.awt.Dimension(50, 50));
        fvermelho4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fvermelho4ActionPerformed(evt);
            }
        });

        cvermelho1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/InterfaceGrafica/vazio.png"))); // NOI18N
        cvermelho1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 0, 0), 3, true));
        cvermelho1.setPreferredSize(new java.awt.Dimension(50, 50));
        cvermelho1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cvermelho1ActionPerformed(evt);
            }
        });

        cvermelho2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/InterfaceGrafica/vazio.png"))); // NOI18N
        cvermelho2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 0, 0), 3, true));
        cvermelho2.setPreferredSize(new java.awt.Dimension(50, 50));
        cvermelho2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cvermelho2ActionPerformed(evt);
            }
        });

        cvermelho3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/InterfaceGrafica/vazio.png"))); // NOI18N
        cvermelho3.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 0, 0), 3, true));
        cvermelho3.setPreferredSize(new java.awt.Dimension(50, 50));
        cvermelho3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cvermelho3ActionPerformed(evt);
            }
        });

        cvermelho4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/InterfaceGrafica/vazio.png"))); // NOI18N
        cvermelho4.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 0, 0), 3, true));
        cvermelho4.setPreferredSize(new java.awt.Dimension(50, 50));
        cvermelho4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cvermelho4ActionPerformed(evt);
            }
        });

        cverde1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/InterfaceGrafica/sem_carta.png"))); // NOI18N
        cverde1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 153, 51), 3, true));
        cverde1.setFocusCycleRoot(true);
        cverde1.setPreferredSize(new java.awt.Dimension(50, 50));
        cverde1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cverde1ActionPerformed(evt);
            }
        });

        cverde2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/InterfaceGrafica/sem_carta.png"))); // NOI18N
        cverde2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 153, 51), 3, true));
        cverde2.setFocusCycleRoot(true);
        cverde2.setPreferredSize(new java.awt.Dimension(50, 50));
        cverde2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cverde2ActionPerformed(evt);
            }
        });

        cverde3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/InterfaceGrafica/sem_carta.png"))); // NOI18N
        cverde3.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 153, 51), 3, true));
        cverde3.setFocusCycleRoot(true);
        cverde3.setPreferredSize(new java.awt.Dimension(50, 50));
        cverde3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cverde3ActionPerformed(evt);
            }
        });

        cverde4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/InterfaceGrafica/sem_carta.png"))); // NOI18N
        cverde4.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 153, 51), 3, true));
        cverde4.setFocusCycleRoot(true);
        cverde4.setPreferredSize(new java.awt.Dimension(50, 50));
        cverde4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cverde4ActionPerformed(evt);
            }
        });

        carta1.setBackground(new java.awt.Color(255, 255, 255));
        carta1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/InterfaceGrafica/sem_carta.png"))); // NOI18N
        carta1.setText("carta1");
        carta1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));

        carta2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/InterfaceGrafica/sem_carta.png"))); // NOI18N
        carta2.setText("carta2");
        carta2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));

        carta3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/InterfaceGrafica/sem_carta.png"))); // NOI18N
        carta3.setText("carta3");
        carta3.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));

        carta4.setBackground(new java.awt.Color(255, 255, 255));
        carta4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/InterfaceGrafica/sem_carta.png"))); // NOI18N
        carta4.setText("carta4");
        carta4.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));

        carta5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/InterfaceGrafica/sem_carta.png"))); // NOI18N
        carta5.setText("carta5");
        carta5.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));

        carta6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/InterfaceGrafica/sem_carta.png"))); // NOI18N
        carta6.setText("cartas jogadas");
        carta6.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));

        descarte.setIcon(new javax.swing.ImageIcon(getClass().getResource("/InterfaceGrafica/sem_carta.png"))); // NOI18N
        descarte.setText("carta6");
        descarte.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(649, 649, 649)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cvermelho2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cvermelho1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, 0)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cvermelho3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cvermelho4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(casa3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(casa1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(casa4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(casa2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(casa5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, 0)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(casa18, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(casa20, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(casa31, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                    .addComponent(casa6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(casa32, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(fverde1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                    .addComponent(casa7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(fverde2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                    .addComponent(casa8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(casa30, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addGroup(layout.createSequentialGroup()
                                                        .addComponent(casa9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addGap(0, 0, 0)
                                                        .addComponent(casa10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addGap(0, 0, 0)
                                                        .addComponent(casa11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addGap(0, 0, 0)
                                                        .addComponent(casa12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addGap(0, 0, 0)
                                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                            .addComponent(fvermelho4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                            .addComponent(casa13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                        .addComponent(casa29, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addGap(0, 0, 0)
                                                        .addComponent(casa28, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addGap(0, 0, 0)
                                                        .addComponent(casa27, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addGap(0, 0, 0)
                                                        .addComponent(casa26, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addGap(0, 0, 0)
                                                        .addComponent(casa25, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addGroup(layout.createSequentialGroup()
                                                        .addComponent(casa14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addGap(0, 0, 0)
                                                        .addComponent(casa15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                    .addGroup(layout.createSequentialGroup()
                                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                            .addComponent(casa24, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                            .addComponent(fvermelho3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                        .addGap(0, 0, 0)
                                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                            .addComponent(fvermelho2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                            .addComponent(casa23, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(fverde3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(0, 0, 0)
                                                .addComponent(fverde4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(casa22, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(0, 0, Short.MAX_VALUE)
                                                .addComponent(casa21, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(casa16, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(0, 0, 0)
                                                .addComponent(casa17, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                .addComponent(fvermelho1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(0, 0, Short.MAX_VALUE)
                                                .addComponent(casa19, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                                .addGap(18, 18, 18)
                                .addComponent(carta6, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(cverde3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, 0)
                                .addComponent(cverde4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(cverde1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, 0)
                                .addComponent(cverde2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(40, 40, 40)
                        .addComponent(carta1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(carta2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(carta3, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(7, 7, 7)
                        .addComponent(carta4, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(carta5, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(7, 7, 7)
                        .addComponent(descarte, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(51, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(cvermelho1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, 0)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(cvermelho2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(93, 93, 93)
                                        .addComponent(casa17, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addGap(143, 143, 143)
                                            .addComponent(casa5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(layout.createSequentialGroup()
                                            .addGap(46, 46, 46)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addComponent(casa15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(casa7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGroup(layout.createSequentialGroup()
                                            .addGap(94, 94, 94)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addComponent(casa16, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(casa6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(casa14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(casa8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(cvermelho4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, 0)
                                .addComponent(cvermelho3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(143, 143, 143)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(casa4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, 0)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(fverde1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(casa3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, 0)
                                        .addComponent(casa2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, 0)
                                        .addComponent(casa1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(fverde4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(fverde2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(fverde3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(casa18, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, 0)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(fvermelho1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(99, 99, 99)
                                        .addComponent(casa22, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(casa19, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(fvermelho3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(fvermelho4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(0, 0, 0)
                                        .addComponent(casa20, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, 0)
                                        .addComponent(casa21, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(fvermelho2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(carta6, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(49, 49, 49))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(casa10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(casa9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(casa11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(casa12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(casa13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(383, 383, 383)
                        .addComponent(casa32, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addComponent(casa31, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(85, 85, 85))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(casa24, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(casa30, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(47, 47, 47))
                        .addComponent(casa29, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(casa28, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(casa27, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(casa26, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(casa25, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(casa23, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(cverde1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(cverde3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(cverde2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(cverde4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(carta1, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(carta2, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(carta3, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(carta4, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(carta5, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(descarte, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void casa4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_casa4ActionPerformed
        // TODO add your handling code here:
       setPecaCasa((JButton) evt.getSource());
    }//GEN-LAST:event_casa4ActionPerformed

    private void casa1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_casa1ActionPerformed
        // TODO add your handling code here:
         setPecaCasa((JButton) evt.getSource());
    }//GEN-LAST:event_casa1ActionPerformed

    private void casa2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_casa2ActionPerformed
        // TODO add your handling code here:
         setPecaCasa((JButton) evt.getSource());
    }//GEN-LAST:event_casa2ActionPerformed

    private void casa3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_casa3ActionPerformed
        // TODO add your handling code here:
         setPecaCasa((JButton) evt.getSource());
    }//GEN-LAST:event_casa3ActionPerformed

    private void casa5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_casa5ActionPerformed
        // TODO add your handling code here:
         setPecaCasa((JButton) evt.getSource());
    }//GEN-LAST:event_casa5ActionPerformed

    private void casa6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_casa6ActionPerformed
        // TODO add your handling code here:
         setPecaCasa((JButton) evt.getSource());
    }//GEN-LAST:event_casa6ActionPerformed

    private void casa7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_casa7ActionPerformed
        // TODO add your handling code here:
         setPecaCasa((JButton) evt.getSource());
    }//GEN-LAST:event_casa7ActionPerformed

    private void casa8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_casa8ActionPerformed
        // TODO add your handling code here:
         setPecaCasa((JButton) evt.getSource());
    }//GEN-LAST:event_casa8ActionPerformed

    private void casa9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_casa9ActionPerformed
        // TODO add your handling code here:
         setPecaCasa((JButton) evt.getSource());
    }//GEN-LAST:event_casa9ActionPerformed

    private void casa10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_casa10ActionPerformed
        // TODO add your handling code here:
         setPecaCasa((JButton) evt.getSource());
    }//GEN-LAST:event_casa10ActionPerformed

    private void casa11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_casa11ActionPerformed
        // TODO add your handling code here:
         setPecaCasa((JButton) evt.getSource());
    }//GEN-LAST:event_casa11ActionPerformed

    private void casa12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_casa12ActionPerformed
        // TODO add your handling code here:
         setPecaCasa((JButton) evt.getSource());
    }//GEN-LAST:event_casa12ActionPerformed

    private void casa13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_casa13ActionPerformed
        // TODO add your handling code here:
         setPecaCasa((JButton) evt.getSource());
    }//GEN-LAST:event_casa13ActionPerformed

    private void casa14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_casa14ActionPerformed
        // TODO add your handling code here:
         setPecaCasa((JButton) evt.getSource());
    }//GEN-LAST:event_casa14ActionPerformed

    private void casa17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_casa17ActionPerformed
        // TODO add your handling code here:
         setPecaCasa((JButton) evt.getSource());
    }//GEN-LAST:event_casa17ActionPerformed

    private void casa15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_casa15ActionPerformed
        // TODO add your handling code here:
         setPecaCasa((JButton) evt.getSource());
    }//GEN-LAST:event_casa15ActionPerformed

    private void casa16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_casa16ActionPerformed
        // TODO add your handling code here:
         setPecaCasa((JButton) evt.getSource());
    }//GEN-LAST:event_casa16ActionPerformed

    private void casa20ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_casa20ActionPerformed
        // TODO add your handling code here:
         setPecaCasa((JButton) evt.getSource());
    }//GEN-LAST:event_casa20ActionPerformed

    private void casa18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_casa18ActionPerformed
        // TODO add your handling code here:
         setPecaCasa((JButton) evt.getSource());
    }//GEN-LAST:event_casa18ActionPerformed

    private void casa19ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_casa19ActionPerformed
        // TODO add your handling code here:
         setPecaCasa((JButton) evt.getSource());
    }//GEN-LAST:event_casa19ActionPerformed

    private void casa21ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_casa21ActionPerformed
        // TODO add your handling code here:
         setPecaCasa((JButton) evt.getSource());
    }//GEN-LAST:event_casa21ActionPerformed

    private void casa22ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_casa22ActionPerformed
        // TODO add your handling code here:
         setPecaCasa((JButton) evt.getSource());
    }//GEN-LAST:event_casa22ActionPerformed

    private void casa25ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_casa25ActionPerformed
        // TODO add your handling code here:
         setPecaCasa((JButton) evt.getSource());
    }//GEN-LAST:event_casa25ActionPerformed

    private void casa23ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_casa23ActionPerformed
        // TODO add your handling code here:
         setPecaCasa((JButton) evt.getSource());
    }//GEN-LAST:event_casa23ActionPerformed

    private void casa24ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_casa24ActionPerformed
        // TODO add your handling code here:
         setPecaCasa((JButton) evt.getSource());
    }//GEN-LAST:event_casa24ActionPerformed

    private void casa26ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_casa26ActionPerformed
        // TODO add your handling code here:
         setPecaCasa((JButton) evt.getSource());
    }//GEN-LAST:event_casa26ActionPerformed

    private void casa27ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_casa27ActionPerformed
        // TODO add your handling code here:
         setPecaCasa((JButton) evt.getSource());
    }//GEN-LAST:event_casa27ActionPerformed

    private void casa28ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_casa28ActionPerformed
        // TODO add your handling code here:
         setPecaCasa((JButton) evt.getSource());
    }//GEN-LAST:event_casa28ActionPerformed

    private void casa29ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_casa29ActionPerformed
        // TODO add your handling code here:
         setPecaCasa((JButton) evt.getSource());
    }//GEN-LAST:event_casa29ActionPerformed

    private void casa30ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_casa30ActionPerformed
        // TODO add your handling code here:
         setPecaCasa((JButton) evt.getSource());
    }//GEN-LAST:event_casa30ActionPerformed

    private void casa31ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_casa31ActionPerformed
        // TODO add your handling code here:
         setPecaCasa((JButton) evt.getSource());
    }//GEN-LAST:event_casa31ActionPerformed

    private void casa32ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_casa32ActionPerformed
        // TODO add your handling code here:
         setPecaCasa((JButton) evt.getSource());
    }//GEN-LAST:event_casa32ActionPerformed

    private void fverde1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fverde1ActionPerformed
        // TODO add your handling code here:
         setPecaCasa((JButton) evt.getSource());
    }//GEN-LAST:event_fverde1ActionPerformed

    private void fverde2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fverde2ActionPerformed
        // TODO add your handling code here:
         setPecaCasa((JButton) evt.getSource());
    }//GEN-LAST:event_fverde2ActionPerformed

    private void fverde3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fverde3ActionPerformed
        // TODO add your handling code here:
         setPecaCasa((JButton) evt.getSource());
    }//GEN-LAST:event_fverde3ActionPerformed

    private void fverde4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fverde4ActionPerformed
        // TODO add your handling code here:
         setPecaCasa((JButton) evt.getSource());
    }//GEN-LAST:event_fverde4ActionPerformed

    private void fvermelho1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fvermelho1ActionPerformed
        // TODO add your handling code here:
         setPecaCasa((JButton) evt.getSource());
    }//GEN-LAST:event_fvermelho1ActionPerformed

    private void fvermelho2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fvermelho2ActionPerformed
        // TODO add your handling code here:
         setPecaCasa((JButton) evt.getSource());
    }//GEN-LAST:event_fvermelho2ActionPerformed

    private void fvermelho3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fvermelho3ActionPerformed
        // TODO add your handling code here:
         setPecaCasa((JButton) evt.getSource());
    }//GEN-LAST:event_fvermelho3ActionPerformed

    private void fvermelho4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fvermelho4ActionPerformed
        // TODO add your handling code here:
         setPecaCasa((JButton) evt.getSource());
    }//GEN-LAST:event_fvermelho4ActionPerformed

    private void cvermelho1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cvermelho1ActionPerformed
        // TODO add your handling code here:
         setPecaCasa((JButton) evt.getSource());
    }//GEN-LAST:event_cvermelho1ActionPerformed

    private void cvermelho2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cvermelho2ActionPerformed
        // TODO add your handling code here:
         setPecaCasa((JButton) evt.getSource());
    }//GEN-LAST:event_cvermelho2ActionPerformed

    private void cvermelho3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cvermelho3ActionPerformed
        // TODO add your handling code here:
         setPecaCasa((JButton) evt.getSource());
    }//GEN-LAST:event_cvermelho3ActionPerformed

    private void cvermelho4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cvermelho4ActionPerformed
        // TODO add your handling code here:
         setPecaCasa((JButton) evt.getSource());
    }//GEN-LAST:event_cvermelho4ActionPerformed

    private void cverde1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cverde1ActionPerformed
        // TODO add your handling code here:
         setPecaCasa((JButton) evt.getSource());
    }//GEN-LAST:event_cverde1ActionPerformed

    private void cverde2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cverde2ActionPerformed
        // TODO add your handling code here:
         setPecaCasa((JButton) evt.getSource());
    }//GEN-LAST:event_cverde2ActionPerformed

    private void cverde3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cverde3ActionPerformed
        // TODO add your handling code here:
         setPecaCasa((JButton) evt.getSource());
    }//GEN-LAST:event_cverde3ActionPerformed

    private void cverde4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cverde4ActionPerformed
        // TODO add your handling code here:
         setPecaCasa((JButton) evt.getSource());
    }//GEN-LAST:event_cverde4ActionPerformed
    
    private void setPecaCasa(JButton casa){
       casa.setIcon(casaverde); 
    }
    
    private Icon getPecaCasa (JButton casa){
       return casa.getIcon();
      }

    public String solictarEnderecoServidor() {
        return JOptionPane.showInputDialog(this, "Digite o Endereço do servidor:", "netgames.labsoft.ufsc.br");
    }

    public String solicitarNomeJogador() {
        return JOptionPane.showInputDialog(this, "Digite o Nome do Jogador:");
    }
    
    public void atualizarInterface(Tabuleiro tabuleiro, int indexjogador){
        Jogador jogador = null;
        Icon icone;
        if(indexjogador == 1){
            icone = casaverde;
            jogador = tabuleiro.getJogadorLocal();
            
        }
        else{
            icone = casavermelho;
            jogador = tabuleiro.getJogadorRemoto();
        } 
        ArrayList<Carta> cartas = jogador.getCartas();
        for(int i =0; i < espacoCartas.size(); i++){
            espacoCartas.get(i).setIcon(casaverde);
            espacoCartas.get(i).setText("carta" + i);
        }
        System.out.println("interface");

    }
    
    public void iniciarTabuleiro(int index){
        espacoCartas = new ArrayList<javax.swing.JLabel>();
        Icon icone;
        if(index == 1)
            icone = casaverde;
        else
             icone = casavermelho;
       espacoCartas.add(carta1);
       espacoCartas.add(carta2);
       espacoCartas.add(carta3);
       espacoCartas.add(carta4);
       espacoCartas.add(carta5);
       espacoCartas.add(carta6);
       
        
    }
   
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel carta1;
    private javax.swing.JLabel carta2;
    private javax.swing.JLabel carta3;
    private javax.swing.JLabel carta4;
    private javax.swing.JLabel carta5;
    private javax.swing.JLabel carta6;
    private javax.swing.JButton casa1;
    private javax.swing.JButton casa10;
    private javax.swing.JButton casa11;
    private javax.swing.JButton casa12;
    private javax.swing.JButton casa13;
    private javax.swing.JButton casa14;
    private javax.swing.JButton casa15;
    private javax.swing.JButton casa16;
    private javax.swing.JButton casa17;
    private javax.swing.JButton casa18;
    private javax.swing.JButton casa19;
    private javax.swing.JButton casa2;
    private javax.swing.JButton casa20;
    private javax.swing.JButton casa21;
    private javax.swing.JButton casa22;
    private javax.swing.JButton casa23;
    private javax.swing.JButton casa24;
    private javax.swing.JButton casa25;
    private javax.swing.JButton casa26;
    private javax.swing.JButton casa27;
    private javax.swing.JButton casa28;
    private javax.swing.JButton casa29;
    private javax.swing.JButton casa3;
    private javax.swing.JButton casa30;
    private javax.swing.JButton casa31;
    private javax.swing.JButton casa32;
    private javax.swing.JButton casa4;
    private javax.swing.JButton casa5;
    private javax.swing.JButton casa6;
    private javax.swing.JButton casa7;
    private javax.swing.JButton casa8;
    private javax.swing.JButton casa9;
    private javax.swing.JButton cverde1;
    private javax.swing.JButton cverde2;
    private javax.swing.JButton cverde3;
    private javax.swing.JButton cverde4;
    private javax.swing.JButton cvermelho1;
    private javax.swing.JButton cvermelho2;
    private javax.swing.JButton cvermelho3;
    private javax.swing.JButton cvermelho4;
    private javax.swing.JLabel descarte;
    private javax.swing.JButton fverde1;
    private javax.swing.JButton fverde2;
    private javax.swing.JButton fverde3;
    private javax.swing.JButton fverde4;
    private javax.swing.JButton fvermelho1;
    private javax.swing.JButton fvermelho2;
    private javax.swing.JButton fvermelho3;
    private javax.swing.JButton fvermelho4;
    // End of variables declaration//GEN-END:variables


}
