package InterfaceGrafica;

import Entidades.Carta;
import Entidades.Jogador;
import Entidades.Tabuleiro;
import java.util.ArrayList;
import javax.swing.Icon;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.

import javax.swing.Icon;
import javax.swing.JButton;

/**
 *
 * @author Carol
 */
public class JPanelTabuleiro extends javax.swing.JPanel {

    Icon casaverde = new javax.swing.ImageIcon(getClass().getResource("verde.png"));
    Icon casavermelho = new javax.swing.ImageIcon(getClass().getResource("vermelho.png"));
    Icon vazio = new javax.swing.ImageIcon(getClass().getResource("vazio.png"));
    
     ArrayList<javax.swing.JButton> casasTabuleiro;
     ArrayList<javax.swing.JButton> espacoCartas;
    AtorJogador ator;
    Icon icone;
    Icon iconeOponente;
    /**
     * Creates new form NewJPanel
     */
    public JPanelTabuleiro() {
        initComponents();
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        casa1 = new javax.swing.JButton();
        casa32 = new javax.swing.JButton();
        casa31 = new javax.swing.JButton();
        casa30 = new javax.swing.JButton();
        casa29 = new javax.swing.JButton();
        casa28 = new javax.swing.JButton();
        casa27 = new javax.swing.JButton();
        casa26 = new javax.swing.JButton();
        casa25 = new javax.swing.JButton();
        casa24 = new javax.swing.JButton();
        casa23 = new javax.swing.JButton();
        casa22 = new javax.swing.JButton();
        casa21 = new javax.swing.JButton();
        casa20 = new javax.swing.JButton();
        casa19 = new javax.swing.JButton();
        casa18 = new javax.swing.JButton();
        casa17 = new javax.swing.JButton();
        casa16 = new javax.swing.JButton();
        casa15 = new javax.swing.JButton();
        casa14 = new javax.swing.JButton();
        casa13 = new javax.swing.JButton();
        casa12 = new javax.swing.JButton();
        casa11 = new javax.swing.JButton();
        casa10 = new javax.swing.JButton();
        casa9 = new javax.swing.JButton();
        casa8 = new javax.swing.JButton();
        casa7 = new javax.swing.JButton();
        casa6 = new javax.swing.JButton();
        casa5 = new javax.swing.JButton();
        casa4 = new javax.swing.JButton();
        casa3 = new javax.swing.JButton();
        casa2 = new javax.swing.JButton();
        fverde1 = new javax.swing.JButton();
        fverde2 = new javax.swing.JButton();
        fverde3 = new javax.swing.JButton();
        fverde4 = new javax.swing.JButton();
        fvermelho1 = new javax.swing.JButton();
        fvermelho2 = new javax.swing.JButton();
        fvermelho3 = new javax.swing.JButton();
        fvermelho4 = new javax.swing.JButton();
        cvermelho1 = new javax.swing.JButton();
        cvermelho2 = new javax.swing.JButton();
        cvermelho3 = new javax.swing.JButton();
        cvermelho4 = new javax.swing.JButton();
        cverde1 = new javax.swing.JButton();
        cverde2 = new javax.swing.JButton();
        cverde3 = new javax.swing.JButton();
        cverde4 = new javax.swing.JButton();
        descarte = new javax.swing.JLabel();
        carta1 = new javax.swing.JButton();
        carta2 = new javax.swing.JButton();
        carta3 = new javax.swing.JButton();
        carta4 = new javax.swing.JButton();
        carta5 = new javax.swing.JButton();
        carta6 = new javax.swing.JButton();
        notificacao = new javax.swing.JLabel();
        peca = new javax.swing.JLabel();
        turno = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setBackground(new java.awt.Color(185, 122, 87));

        casa1.setFont(new java.awt.Font("Tahoma", 0, 3)); // NOI18N
        casa1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/InterfaceGrafica/vazio.png"))); // NOI18N
        casa1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 153, 0), 3));
        casa1.setPreferredSize(new java.awt.Dimension(50, 50));
        casa1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                casa1ActionPerformed(evt);
            }
        });

        casa32.setFont(new java.awt.Font("Tahoma", 0, 3)); // NOI18N
        casa32.setIcon(new javax.swing.ImageIcon(getClass().getResource("/InterfaceGrafica/vazio.png"))); // NOI18N
        casa32.setPreferredSize(new java.awt.Dimension(50, 50));
        casa32.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                casa32ActionPerformed(evt);
            }
        });

        casa31.setFont(new java.awt.Font("Tahoma", 0, 3)); // NOI18N
        casa31.setIcon(new javax.swing.ImageIcon(getClass().getResource("/InterfaceGrafica/vazio.png"))); // NOI18N
        casa31.setPreferredSize(new java.awt.Dimension(50, 50));
        casa31.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                casa31ActionPerformed(evt);
            }
        });

        casa30.setFont(new java.awt.Font("Tahoma", 0, 3)); // NOI18N
        casa30.setIcon(new javax.swing.ImageIcon(getClass().getResource("/InterfaceGrafica/vazio.png"))); // NOI18N
        casa30.setPreferredSize(new java.awt.Dimension(50, 50));
        casa30.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                casa30ActionPerformed(evt);
            }
        });

        casa29.setFont(new java.awt.Font("Tahoma", 0, 3)); // NOI18N
        casa29.setIcon(new javax.swing.ImageIcon(getClass().getResource("/InterfaceGrafica/vazio.png"))); // NOI18N
        casa29.setPreferredSize(new java.awt.Dimension(50, 50));
        casa29.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                casa29ActionPerformed(evt);
            }
        });

        casa28.setFont(new java.awt.Font("Tahoma", 0, 3)); // NOI18N
        casa28.setIcon(new javax.swing.ImageIcon(getClass().getResource("/InterfaceGrafica/vazio.png"))); // NOI18N
        casa28.setPreferredSize(new java.awt.Dimension(50, 50));
        casa28.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                casa28ActionPerformed(evt);
            }
        });

        casa27.setFont(new java.awt.Font("Tahoma", 0, 3)); // NOI18N
        casa27.setIcon(new javax.swing.ImageIcon(getClass().getResource("/InterfaceGrafica/vazio.png"))); // NOI18N
        casa27.setPreferredSize(new java.awt.Dimension(50, 50));
        casa27.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                casa27ActionPerformed(evt);
            }
        });

        casa26.setFont(new java.awt.Font("Tahoma", 0, 3)); // NOI18N
        casa26.setIcon(new javax.swing.ImageIcon(getClass().getResource("/InterfaceGrafica/vazio.png"))); // NOI18N
        casa26.setPreferredSize(new java.awt.Dimension(50, 50));
        casa26.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                casa26ActionPerformed(evt);
            }
        });

        casa25.setFont(new java.awt.Font("Tahoma", 0, 3)); // NOI18N
        casa25.setIcon(new javax.swing.ImageIcon(getClass().getResource("/InterfaceGrafica/vazio.png"))); // NOI18N
        casa25.setPreferredSize(new java.awt.Dimension(50, 50));
        casa25.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                casa25ActionPerformed(evt);
            }
        });

        casa24.setFont(new java.awt.Font("Tahoma", 0, 3)); // NOI18N
        casa24.setIcon(new javax.swing.ImageIcon(getClass().getResource("/InterfaceGrafica/vazio.png"))); // NOI18N
        casa24.setPreferredSize(new java.awt.Dimension(50, 50));
        casa24.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                casa24ActionPerformed(evt);
            }
        });

        casa23.setFont(new java.awt.Font("Tahoma", 0, 3)); // NOI18N
        casa23.setIcon(new javax.swing.ImageIcon(getClass().getResource("/InterfaceGrafica/vazio.png"))); // NOI18N
        casa23.setPreferredSize(new java.awt.Dimension(50, 50));
        casa23.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                casa23ActionPerformed(evt);
            }
        });

        casa22.setFont(new java.awt.Font("Tahoma", 0, 3)); // NOI18N
        casa22.setIcon(new javax.swing.ImageIcon(getClass().getResource("/InterfaceGrafica/vazio.png"))); // NOI18N
        casa22.setPreferredSize(new java.awt.Dimension(50, 50));
        casa22.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                casa22ActionPerformed(evt);
            }
        });

        casa21.setFont(new java.awt.Font("Tahoma", 0, 3)); // NOI18N
        casa21.setIcon(new javax.swing.ImageIcon(getClass().getResource("/InterfaceGrafica/vazio.png"))); // NOI18N
        casa21.setPreferredSize(new java.awt.Dimension(50, 50));
        casa21.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                casa21ActionPerformed(evt);
            }
        });

        casa20.setFont(new java.awt.Font("Tahoma", 0, 3)); // NOI18N
        casa20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/InterfaceGrafica/vazio.png"))); // NOI18N
        casa20.setPreferredSize(new java.awt.Dimension(50, 50));
        casa20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                casa20ActionPerformed(evt);
            }
        });

        casa19.setFont(new java.awt.Font("Tahoma", 0, 3)); // NOI18N
        casa19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/InterfaceGrafica/vazio.png"))); // NOI18N
        casa19.setPreferredSize(new java.awt.Dimension(50, 50));
        casa19.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                casa19ActionPerformed(evt);
            }
        });

        casa18.setFont(new java.awt.Font("Tahoma", 0, 3)); // NOI18N
        casa18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/InterfaceGrafica/vazio.png"))); // NOI18N
        casa18.setPreferredSize(new java.awt.Dimension(50, 50));
        casa18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                casa18ActionPerformed(evt);
            }
        });

        casa17.setFont(new java.awt.Font("Tahoma", 0, 3)); // NOI18N
        casa17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/InterfaceGrafica/vazio.png"))); // NOI18N
        casa17.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 0, 0), 3));
        casa17.setPreferredSize(new java.awt.Dimension(50, 50));
        casa17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                casa17ActionPerformed(evt);
            }
        });

        casa16.setFont(new java.awt.Font("Tahoma", 0, 3)); // NOI18N
        casa16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/InterfaceGrafica/vazio.png"))); // NOI18N
        casa16.setPreferredSize(new java.awt.Dimension(50, 50));
        casa16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                casa16ActionPerformed(evt);
            }
        });

        casa15.setFont(new java.awt.Font("Tahoma", 0, 3)); // NOI18N
        casa15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/InterfaceGrafica/vazio.png"))); // NOI18N
        casa15.setPreferredSize(new java.awt.Dimension(50, 50));
        casa15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                casa15ActionPerformed(evt);
            }
        });

        casa14.setFont(new java.awt.Font("Tahoma", 0, 3)); // NOI18N
        casa14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/InterfaceGrafica/vazio.png"))); // NOI18N
        casa14.setPreferredSize(new java.awt.Dimension(50, 50));
        casa14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                casa14ActionPerformed(evt);
            }
        });

        casa13.setFont(new java.awt.Font("Tahoma", 0, 3)); // NOI18N
        casa13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/InterfaceGrafica/vazio.png"))); // NOI18N
        casa13.setPreferredSize(new java.awt.Dimension(50, 50));
        casa13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                casa13ActionPerformed(evt);
            }
        });

        casa12.setFont(new java.awt.Font("Tahoma", 0, 3)); // NOI18N
        casa12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/InterfaceGrafica/vazio.png"))); // NOI18N
        casa12.setPreferredSize(new java.awt.Dimension(50, 50));
        casa12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                casa12ActionPerformed(evt);
            }
        });

        casa11.setFont(new java.awt.Font("Tahoma", 0, 3)); // NOI18N
        casa11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/InterfaceGrafica/vazio.png"))); // NOI18N
        casa11.setPreferredSize(new java.awt.Dimension(50, 50));
        casa11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                casa11ActionPerformed(evt);
            }
        });

        casa10.setFont(new java.awt.Font("Tahoma", 0, 3)); // NOI18N
        casa10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/InterfaceGrafica/vazio.png"))); // NOI18N
        casa10.setPreferredSize(new java.awt.Dimension(50, 50));
        casa10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                casa10ActionPerformed(evt);
            }
        });

        casa9.setFont(new java.awt.Font("Tahoma", 0, 3)); // NOI18N
        casa9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/InterfaceGrafica/vazio.png"))); // NOI18N
        casa9.setPreferredSize(new java.awt.Dimension(50, 50));
        casa9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                casa9ActionPerformed(evt);
            }
        });

        casa8.setFont(new java.awt.Font("Tahoma", 0, 3)); // NOI18N
        casa8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/InterfaceGrafica/vazio.png"))); // NOI18N
        casa8.setPreferredSize(new java.awt.Dimension(50, 50));
        casa8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                casa8ActionPerformed(evt);
            }
        });

        casa7.setFont(new java.awt.Font("Tahoma", 0, 3)); // NOI18N
        casa7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/InterfaceGrafica/vazio.png"))); // NOI18N
        casa7.setPreferredSize(new java.awt.Dimension(50, 50));
        casa7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                casa7ActionPerformed(evt);
            }
        });

        casa6.setFont(new java.awt.Font("Tahoma", 0, 3)); // NOI18N
        casa6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/InterfaceGrafica/vazio.png"))); // NOI18N
        casa6.setPreferredSize(new java.awt.Dimension(50, 50));
        casa6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                casa6ActionPerformed(evt);
            }
        });

        casa5.setFont(new java.awt.Font("Tahoma", 0, 3)); // NOI18N
        casa5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/InterfaceGrafica/vazio.png"))); // NOI18N
        casa5.setPreferredSize(new java.awt.Dimension(50, 50));
        casa5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                casa5ActionPerformed(evt);
            }
        });

        casa4.setFont(new java.awt.Font("Tahoma", 0, 3)); // NOI18N
        casa4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/InterfaceGrafica/vazio.png"))); // NOI18N
        casa4.setPreferredSize(new java.awt.Dimension(50, 50));
        casa4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                casa4ActionPerformed(evt);
            }
        });

        casa3.setFont(new java.awt.Font("Tahoma", 0, 3)); // NOI18N
        casa3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/InterfaceGrafica/vazio.png"))); // NOI18N
        casa3.setPreferredSize(new java.awt.Dimension(50, 50));
        casa3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                casa3ActionPerformed(evt);
            }
        });

        casa2.setFont(new java.awt.Font("Tahoma", 0, 3)); // NOI18N
        casa2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/InterfaceGrafica/vazio.png"))); // NOI18N
        casa2.setPreferredSize(new java.awt.Dimension(50, 50));
        casa2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                casa2ActionPerformed(evt);
            }
        });

        fverde1.setFont(new java.awt.Font("Tahoma", 0, 3)); // NOI18N
        fverde1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/InterfaceGrafica/vazio.png"))); // NOI18N
        fverde1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 153, 51), 3, true));
        fverde1.setPreferredSize(new java.awt.Dimension(50, 50));
        fverde1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fverde1ActionPerformed(evt);
            }
        });

        fverde2.setFont(new java.awt.Font("Tahoma", 0, 3)); // NOI18N
        fverde2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/InterfaceGrafica/vazio.png"))); // NOI18N
        fverde2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 153, 51), 3, true));
        fverde2.setPreferredSize(new java.awt.Dimension(50, 50));
        fverde2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fverde2ActionPerformed(evt);
            }
        });

        fverde3.setFont(new java.awt.Font("Tahoma", 0, 3)); // NOI18N
        fverde3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/InterfaceGrafica/vazio.png"))); // NOI18N
        fverde3.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 153, 51), 3, true));
        fverde3.setPreferredSize(new java.awt.Dimension(50, 50));
        fverde3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fverde3ActionPerformed(evt);
            }
        });

        fverde4.setFont(new java.awt.Font("Tahoma", 0, 3)); // NOI18N
        fverde4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/InterfaceGrafica/vazio.png"))); // NOI18N
        fverde4.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 153, 51), 3, true));
        fverde4.setPreferredSize(new java.awt.Dimension(50, 50));
        fverde4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fverde4ActionPerformed(evt);
            }
        });

        fvermelho1.setFont(new java.awt.Font("Tahoma", 0, 3)); // NOI18N
        fvermelho1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/InterfaceGrafica/vazio.png"))); // NOI18N
        fvermelho1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 0, 0), 3, true));
        fvermelho1.setPreferredSize(new java.awt.Dimension(50, 50));
        fvermelho1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fvermelho1ActionPerformed(evt);
            }
        });

        fvermelho2.setFont(new java.awt.Font("Tahoma", 0, 3)); // NOI18N
        fvermelho2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/InterfaceGrafica/vazio.png"))); // NOI18N
        fvermelho2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 0, 0), 3, true));
        fvermelho2.setPreferredSize(new java.awt.Dimension(50, 50));
        fvermelho2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fvermelho2ActionPerformed(evt);
            }
        });

        fvermelho3.setFont(new java.awt.Font("Tahoma", 0, 3)); // NOI18N
        fvermelho3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/InterfaceGrafica/vazio.png"))); // NOI18N
        fvermelho3.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 0, 0), 3, true));
        fvermelho3.setPreferredSize(new java.awt.Dimension(50, 50));
        fvermelho3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fvermelho3ActionPerformed(evt);
            }
        });

        fvermelho4.setFont(new java.awt.Font("Tahoma", 0, 3)); // NOI18N
        fvermelho4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/InterfaceGrafica/vazio.png"))); // NOI18N
        fvermelho4.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 0, 0), 3, true));
        fvermelho4.setPreferredSize(new java.awt.Dimension(50, 50));
        fvermelho4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fvermelho4ActionPerformed(evt);
            }
        });

        cvermelho1.setFont(new java.awt.Font("Tahoma", 0, 3)); // NOI18N
        cvermelho1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/InterfaceGrafica/vazio.png"))); // NOI18N
        cvermelho1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 0, 0), 3, true));
        cvermelho1.setPreferredSize(new java.awt.Dimension(50, 50));
        cvermelho1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cvermelho1ActionPerformed(evt);
            }
        });

        cvermelho2.setFont(new java.awt.Font("Tahoma", 0, 3)); // NOI18N
        cvermelho2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/InterfaceGrafica/vazio.png"))); // NOI18N
        cvermelho2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 0, 0), 3, true));
        cvermelho2.setPreferredSize(new java.awt.Dimension(50, 50));
        cvermelho2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cvermelho2ActionPerformed(evt);
            }
        });

        cvermelho3.setFont(new java.awt.Font("Tahoma", 0, 3)); // NOI18N
        cvermelho3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/InterfaceGrafica/vazio.png"))); // NOI18N
        cvermelho3.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 0, 0), 3, true));
        cvermelho3.setPreferredSize(new java.awt.Dimension(50, 50));
        cvermelho3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cvermelho3ActionPerformed(evt);
            }
        });

        cvermelho4.setFont(new java.awt.Font("Tahoma", 0, 3)); // NOI18N
        cvermelho4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/InterfaceGrafica/vazio.png"))); // NOI18N
        cvermelho4.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 0, 0), 3, true));
        cvermelho4.setPreferredSize(new java.awt.Dimension(50, 50));
        cvermelho4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cvermelho4ActionPerformed(evt);
            }
        });

        cverde1.setFont(new java.awt.Font("Tahoma", 0, 3)); // NOI18N
        cverde1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/InterfaceGrafica/vazio.png"))); // NOI18N
        cverde1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 153, 51), 3, true));
        cverde1.setFocusCycleRoot(true);
        cverde1.setPreferredSize(new java.awt.Dimension(50, 50));
        cverde1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cverde1ActionPerformed(evt);
            }
        });

        cverde2.setFont(new java.awt.Font("Tahoma", 0, 3)); // NOI18N
        cverde2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/InterfaceGrafica/vazio.png"))); // NOI18N
        cverde2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 153, 51), 3, true));
        cverde2.setFocusCycleRoot(true);
        cverde2.setPreferredSize(new java.awt.Dimension(50, 50));
        cverde2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cverde2ActionPerformed(evt);
            }
        });

        cverde3.setFont(new java.awt.Font("Tahoma", 0, 3)); // NOI18N
        cverde3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/InterfaceGrafica/vazio.png"))); // NOI18N
        cverde3.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 153, 51), 3, true));
        cverde3.setFocusCycleRoot(true);
        cverde3.setPreferredSize(new java.awt.Dimension(50, 50));
        cverde3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cverde3ActionPerformed(evt);
            }
        });

        cverde4.setFont(new java.awt.Font("Tahoma", 0, 3)); // NOI18N
        cverde4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/InterfaceGrafica/vazio.png"))); // NOI18N
        cverde4.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 153, 51), 3, true));
        cverde4.setFocusCycleRoot(true);
        cverde4.setPreferredSize(new java.awt.Dimension(50, 50));
        cverde4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cverde4ActionPerformed(evt);
            }
        });

        descarte.setText("cartas jogadas");
        descarte.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));

        carta1.setText("carta");
        carta1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                carta1ActionPerformed(evt);
            }
        });

        carta2.setText("carta");
        carta2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                carta2ActionPerformed(evt);
            }
        });

        carta3.setText("carta");
        carta3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                carta3ActionPerformed(evt);
            }
        });

        carta4.setText("carta");
        carta4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                carta4ActionPerformed(evt);
            }
        });

        carta5.setText("carta");
        carta5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                carta5ActionPerformed(evt);
            }
        });

        carta6.setText("carta");
        carta6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                carta6ActionPerformed(evt);
            }
        });

        notificacao.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        notificacao.setText("Notificacões");

        peca.setText("Suas peças são ---");

        turno.setText("Jogador da vez");

        jLabel1.setText("Ultimo descarte:");

        jButton1.setText("Descartar Carta");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(624, 624, 624)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(cvermelho2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(cvermelho1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(0, 0, 0)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(cvermelho3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(cvermelho4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(casa31, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(casa1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(casa30, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(casa32, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(casa29, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(casa16, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(casa14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGap(18, 18, 18)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(descarte, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(casa3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(layout.createSequentialGroup()
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addComponent(casa28, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(casa2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(fverde1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addComponent(casa27, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(fverde2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addComponent(casa26, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(casa4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(layout.createSequentialGroup()
                                                    .addComponent(casa25, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addGap(0, 0, 0)
                                                    .addComponent(casa24, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addGap(0, 0, 0)
                                                    .addComponent(casa23, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addGap(0, 0, 0)
                                                    .addComponent(casa22, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addGap(0, 0, 0)
                                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(fvermelho4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(casa21, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                    .addComponent(casa5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addGap(0, 0, 0)
                                                    .addComponent(casa6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addGap(0, 0, 0)
                                                    .addComponent(casa7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addGap(0, 0, 0)
                                                    .addComponent(casa8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addGap(0, 0, 0)
                                                    .addComponent(casa9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(layout.createSequentialGroup()
                                                    .addComponent(casa20, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addGap(0, 0, 0)
                                                    .addComponent(casa19, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGroup(layout.createSequentialGroup()
                                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(casa10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(fvermelho3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                    .addGap(0, 0, 0)
                                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(fvermelho2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(casa11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(fverde3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(0, 0, 0)
                                            .addComponent(fverde4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(casa18, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(0, 0, 0)
                                            .addComponent(casa17, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                            .addComponent(fvermelho1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(0, 0, Short.MAX_VALUE)
                                            .addComponent(casa15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 118, Short.MAX_VALUE))
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(casa12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(0, 0, Short.MAX_VALUE)
                                            .addComponent(casa13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 118, Short.MAX_VALUE))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(jButton1)
                                            .addGap(30, 30, 30)))))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(cverde3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, 0)
                                        .addComponent(cverde4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(cverde1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, 0)
                                        .addComponent(cverde2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(56, 56, 56))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(peca, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                        .addGap(0, 0, 0)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(turno, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(notificacao, javax.swing.GroupLayout.PREFERRED_SIZE, 489, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(carta1, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(carta2, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(carta3, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(carta4, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(carta5, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(carta6, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(20, 20, 20))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(cvermelho1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, 0)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(cvermelho2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(93, 93, 93)
                                        .addComponent(casa17, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addGap(143, 143, 143)
                                            .addComponent(casa29, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(layout.createSequentialGroup()
                                            .addGap(46, 46, 46)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addComponent(casa19, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(casa27, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGroup(layout.createSequentialGroup()
                                            .addGap(94, 94, 94)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addComponent(casa18, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(casa28, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(casa20, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(casa26, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(cvermelho4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, 0)
                                .addComponent(cvermelho3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(143, 143, 143)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(casa30, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, 0)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(fverde1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(casa31, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, 0)
                                        .addComponent(casa32, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, 0)
                                        .addComponent(casa1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(fverde4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(fverde2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(fverde3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(casa16, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, 0)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(fvermelho1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(99, 99, 99)
                                        .addComponent(casa12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(casa15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(fvermelho3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(fvermelho4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(0, 0, 0)
                                        .addComponent(casa14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, 0)
                                        .addComponent(casa13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(fvermelho2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(descarte, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(49, 49, 49))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(casa24, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(casa25, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(casa23, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(casa22, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(casa21, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(383, 383, 383)
                        .addComponent(casa2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addComponent(casa3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(99, 99, 99))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(casa10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(casa4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGap(47, 47, 47))
                                .addComponent(casa5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(casa6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(casa7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(casa8, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(casa9, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(casa11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton1)
                        .addGap(83, 83, 83)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(notificacao, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(peca)
                    .addComponent(turno))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(carta6, javax.swing.GroupLayout.DEFAULT_SIZE, 144, Short.MAX_VALUE)
                    .addComponent(carta5, javax.swing.GroupLayout.DEFAULT_SIZE, 144, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(cverde1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(cverde3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(cverde2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(cverde4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(carta1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(carta2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(carta3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(carta4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(20, 20, 20))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void casa30ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_casa30ActionPerformed
        // TODO add your handling code here:
       setPecaCasa((JButton) evt.getSource());
    }//GEN-LAST:event_casa30ActionPerformed

    private void casa1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_casa1ActionPerformed
        // TODO add your handling code here:
         setPecaCasa((JButton) evt.getSource());
    }//GEN-LAST:event_casa1ActionPerformed

    private void casa32ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_casa32ActionPerformed
        // TODO add your handling code here:
         setPecaCasa((JButton) evt.getSource());
    }//GEN-LAST:event_casa32ActionPerformed

    private void casa31ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_casa31ActionPerformed
        // TODO add your handling code here:
         setPecaCasa((JButton) evt.getSource());
    }//GEN-LAST:event_casa31ActionPerformed

    private void casa29ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_casa29ActionPerformed
        // TODO add your handling code here:
         setPecaCasa((JButton) evt.getSource());
    }//GEN-LAST:event_casa29ActionPerformed

    private void casa28ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_casa28ActionPerformed
        // TODO add your handling code here:
         setPecaCasa((JButton) evt.getSource());
    }//GEN-LAST:event_casa28ActionPerformed

    private void casa27ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_casa27ActionPerformed
        // TODO add your handling code here:
         setPecaCasa((JButton) evt.getSource());
    }//GEN-LAST:event_casa27ActionPerformed

    private void casa26ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_casa26ActionPerformed
        // TODO add your handling code here:
         setPecaCasa((JButton) evt.getSource());
    }//GEN-LAST:event_casa26ActionPerformed

    private void casa25ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_casa25ActionPerformed
        // TODO add your handling code here:
         setPecaCasa((JButton) evt.getSource());
    }//GEN-LAST:event_casa25ActionPerformed

    private void casa24ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_casa24ActionPerformed
        // TODO add your handling code here:
         setPecaCasa((JButton) evt.getSource());
    }//GEN-LAST:event_casa24ActionPerformed

    private void casa23ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_casa23ActionPerformed
        // TODO add your handling code here:
         setPecaCasa((JButton) evt.getSource());
    }//GEN-LAST:event_casa23ActionPerformed

    private void casa22ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_casa22ActionPerformed
        // TODO add your handling code here:
         setPecaCasa((JButton) evt.getSource());
    }//GEN-LAST:event_casa22ActionPerformed

    private void casa21ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_casa21ActionPerformed
        // TODO add your handling code here:
         setPecaCasa((JButton) evt.getSource());
    }//GEN-LAST:event_casa21ActionPerformed

    private void casa20ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_casa20ActionPerformed
        // TODO add your handling code here:
         setPecaCasa((JButton) evt.getSource());
    }//GEN-LAST:event_casa20ActionPerformed

    private void casa17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_casa17ActionPerformed
        // TODO add your handling code here:
         setPecaCasa((JButton) evt.getSource());
    }//GEN-LAST:event_casa17ActionPerformed

    private void casa19ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_casa19ActionPerformed
        // TODO add your handling code here:
         setPecaCasa((JButton) evt.getSource());
    }//GEN-LAST:event_casa19ActionPerformed

    private void casa18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_casa18ActionPerformed
        // TODO add your handling code here:
         setPecaCasa((JButton) evt.getSource());
    }//GEN-LAST:event_casa18ActionPerformed

    private void casa14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_casa14ActionPerformed
        // TODO add your handling code here:
         setPecaCasa((JButton) evt.getSource());
    }//GEN-LAST:event_casa14ActionPerformed

    private void casa16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_casa16ActionPerformed
        // TODO add your handling code here:
         setPecaCasa((JButton) evt.getSource());
    }//GEN-LAST:event_casa16ActionPerformed

    private void casa15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_casa15ActionPerformed
        // TODO add your handling code here:
         setPecaCasa((JButton) evt.getSource());
    }//GEN-LAST:event_casa15ActionPerformed

    private void casa13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_casa13ActionPerformed
        // TODO add your handling code here:
         setPecaCasa((JButton) evt.getSource());
    }//GEN-LAST:event_casa13ActionPerformed

    private void casa12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_casa12ActionPerformed
        // TODO add your handling code here:
         setPecaCasa((JButton) evt.getSource());
    }//GEN-LAST:event_casa12ActionPerformed

    private void casa9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_casa9ActionPerformed
        // TODO add your handling code here:
         setPecaCasa((JButton) evt.getSource());
    }//GEN-LAST:event_casa9ActionPerformed

    private void casa11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_casa11ActionPerformed
        // TODO add your handling code here:
         setPecaCasa((JButton) evt.getSource());
    }//GEN-LAST:event_casa11ActionPerformed

    private void casa10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_casa10ActionPerformed
        // TODO add your handling code here:
         setPecaCasa((JButton) evt.getSource());
    }//GEN-LAST:event_casa10ActionPerformed

    private void casa8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_casa8ActionPerformed
        // TODO add your handling code here:
         setPecaCasa((JButton) evt.getSource());
    }//GEN-LAST:event_casa8ActionPerformed

    private void casa7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_casa7ActionPerformed
        // TODO add your handling code here:
         setPecaCasa((JButton) evt.getSource());
    }//GEN-LAST:event_casa7ActionPerformed

    private void casa6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_casa6ActionPerformed
        // TODO add your handling code here:
         setPecaCasa((JButton) evt.getSource());
    }//GEN-LAST:event_casa6ActionPerformed

    private void casa5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_casa5ActionPerformed
        // TODO add your handling code here:
         setPecaCasa((JButton) evt.getSource());
    }//GEN-LAST:event_casa5ActionPerformed

    private void casa4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_casa4ActionPerformed
        // TODO add your handling code here:
         setPecaCasa((JButton) evt.getSource());
    }//GEN-LAST:event_casa4ActionPerformed

    private void casa3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_casa3ActionPerformed
        // TODO add your handling code here:
         setPecaCasa((JButton) evt.getSource());
    }//GEN-LAST:event_casa3ActionPerformed

    private void casa2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_casa2ActionPerformed
        // TODO add your handling code here:
         setPecaCasa((JButton) evt.getSource());
    }//GEN-LAST:event_casa2ActionPerformed

    private void fverde1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fverde1ActionPerformed
        // TODO add your handling code here:
         moverPecaFim("fverde1");
    }//GEN-LAST:event_fverde1ActionPerformed

    private void fverde2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fverde2ActionPerformed
        // TODO add your handling code here:
         moverPecaFim("fverde2");
    }//GEN-LAST:event_fverde2ActionPerformed

    private void fverde3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fverde3ActionPerformed
        // TODO add your handling code here:
          moverPecaFim("fverde3");
    }//GEN-LAST:event_fverde3ActionPerformed

    private void fverde4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fverde4ActionPerformed
        // TODO add your handling code here:
          moverPecaFim("fverde4");
    }//GEN-LAST:event_fverde4ActionPerformed

    private void fvermelho1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fvermelho1ActionPerformed
        // TODO add your handling code here:
          moverPecaFim("fvermelho1");
    }//GEN-LAST:event_fvermelho1ActionPerformed

    private void fvermelho2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fvermelho2ActionPerformed
        // TODO add your handling code here:
         moverPecaFim("fvermelho2");
    }//GEN-LAST:event_fvermelho2ActionPerformed

    private void fvermelho3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fvermelho3ActionPerformed
        // TODO add your handling code here:
         moverPecaFim("fvermelho3");
    }//GEN-LAST:event_fvermelho3ActionPerformed

    private void fvermelho4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fvermelho4ActionPerformed
        // TODO add your handling code here:
          moverPecaFim("fvermelho4");
    }//GEN-LAST:event_fvermelho4ActionPerformed

    private void cvermelho1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cvermelho1ActionPerformed
        // TODO add your handling code here:
          moverPecaInicio("cvermelho1");
    }//GEN-LAST:event_cvermelho1ActionPerformed

    private void cvermelho2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cvermelho2ActionPerformed
        // TODO add your handling code here:
          moverPecaInicio("cvermelho2");
    }//GEN-LAST:event_cvermelho2ActionPerformed

    private void cvermelho3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cvermelho3ActionPerformed
        // TODO add your handling code here:
          moverPecaInicio("cvermelho3");
    }//GEN-LAST:event_cvermelho3ActionPerformed

    private void cvermelho4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cvermelho4ActionPerformed
        // TODO add your handling code here:
        moverPecaInicio("cvermelho4");
    }//GEN-LAST:event_cvermelho4ActionPerformed

    private void cverde1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cverde1ActionPerformed
        // TODO add your handling code here:
        
         moverPecaInicio("cverde1");
    }//GEN-LAST:event_cverde1ActionPerformed

    private void cverde2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cverde2ActionPerformed
        // TODO add your handling code here:
          moverPecaInicio("cverde2");
    }//GEN-LAST:event_cverde2ActionPerformed

    private void cverde3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cverde3ActionPerformed
        // TODO add your handling code here:
         moverPecaInicio("cverde3");
    }//GEN-LAST:event_cverde3ActionPerformed

    private void cverde4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cverde4ActionPerformed
        // TODO add your handling code here:
          moverPecaInicio("cverde4");
    }//GEN-LAST:event_cverde4ActionPerformed

    private void carta1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_carta1ActionPerformed
        // TODO add your handling code here:
         selecionarCarta(carta1);
    }//GEN-LAST:event_carta1ActionPerformed

    private void carta4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_carta4ActionPerformed
        // TODO add your handling code here:
        selecionarCarta(carta4);
    }//GEN-LAST:event_carta4ActionPerformed

    private void carta2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_carta2ActionPerformed
        // TODO add your handling code here:
         selecionarCarta(carta2);
    }//GEN-LAST:event_carta2ActionPerformed

    private void carta3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_carta3ActionPerformed
        // TODO add your handling code here:
         selecionarCarta(carta3);
    }//GEN-LAST:event_carta3ActionPerformed

    private void carta5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_carta5ActionPerformed
        // TODO add your handling code here:
         selecionarCarta(carta5);
    }//GEN-LAST:event_carta5ActionPerformed

    private void carta6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_carta6ActionPerformed
        // TODO add your handling code here:
         selecionarCarta(carta6);
    }//GEN-LAST:event_carta6ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        this.ator.descartar();
    }//GEN-LAST:event_jButton1ActionPerformed

    public AtorJogador getAtor() {
        return ator;
    }

    public void setAtor(AtorJogador ator) {
        this.ator = ator;
    }
    
    
    //metodo implementado nas casas iniciais
    public void moverPecaInicio(String casa ){
        
        ator.moverPecaInicio(casa);
        
    }
    
    public void moverPecaFim(String casa){
        
    }
           

    
    //metodo implementado nos campos de carta
    private void selecionarCarta(JButton carta){
        ator.selecionarCarta(carta.getText());
    }
    
    //ainda n tem utilidade, apenas coloca as bolinhas nos botoes clicacos
    private void setPecaCasa(JButton casa){
        
             this.ator.moverPecaEmJogo(casa.getText());
    }
    
    
    private Icon getPecaCasa (JButton casa){
       return casa.getIcon();
      }

    
    
    //aqui q o endereco e definido
    public String solictarEnderecoServidor() {
        return JOptionPane.showInputDialog(this, "Digite o Endereço do servidor:", "netgames.labsoft.ufsc.br");
    }

    public String solicitarNomeJogador() {
        return JOptionPane.showInputDialog(this, "Digite o Nome do Jogador:");
    }
    
    
    //metodo que recebe o tabuleiro atual, e com base nele modifica os elementos da interface (coloca as cartas, mexe as casas e etc)
    public void atualizarInterface(Tabuleiro tabuleiro){
        Jogador jogador;
        Jogador jogador2;
       
        Icon icone;
        if(tabuleiro.getJogadorLocal().getCor() == ator.getOrdem()){
            jogador = tabuleiro.getJogadorLocal();
            jogador2 = tabuleiro.getJogadorRemoto();
        }
        else{ 
            jogador = tabuleiro.getJogadorRemoto();
            jogador2 = tabuleiro.getJogadorLocal();

        }
        String turno = "Vez do oponente";
        if(jogador.isTurno()){
            turno = "Sua vez";
        }
         this.turno.setText(turno);
        //instancia os arrays necessarios para atualizar cartas e casas
        if(tabuleiro.getRodada() == 1)
             iniciarTabuleiro(tabuleiro);
        
        
        //atualiza a interface de cartas de cada jogador 
        ArrayList<Carta> cartas = jogador.getCartas();
        for(int i =0; i < espacoCartas.size(); i++){
            if(cartas != null && i < cartas.size())
                espacoCartas.get(i).setText("" + cartas.get(i).getNumero());
            else 
                espacoCartas.get(i).setText("");
        }
        
        if(jogador.getCartaEscolhida() != null){
            descarte.setText("" + jogador.getCartaEscolhida().getNumero());
        }
        else if(jogador2.getCartaEscolhida() != null)
            descarte.setText("" + jogador2.getCartaEscolhida().getNumero());
        
        
        //informa se o oponente teve as cartas descartadas
        if(jogador2.isDescartado())
            this.notificar("As cartas do adversario foram descartadas");
        
        
        //vai varrer o array posicoespeca do tabuleiro e atualizar a interface com as casas ocupadas
        ArrayList<String> posicoes = tabuleiro.getPosicaoPecas();
        System.out.println(posicoes);
            
            for(JButton casa : this.casasTabuleiro){
                for(int i = 0; i < posicoes.size(); i++){
                casa.setIcon(vazio);
                if(casa.getText().equalsIgnoreCase(posicoes.get(i))){
                    //as primeiras quatro pecas do array sao do jogador verde
                    if(i < 4)
                        casa.setIcon(casaverde);
                    //as outras sao do jogador vermelho
                    else
                        casa.setIcon(casavermelho);
                    break;
                }   
            }
        }
    }
    
    
    //inicia algumas variaveis para usar na interface
    public void iniciarTabuleiro(Tabuleiro tabuleiro){
        espacoCartas = new ArrayList<javax.swing.JButton>();
        casasTabuleiro = new ArrayList<javax.swing.JButton>();
        if(tabuleiro.getJogadorLocal().getCor() == ator.getOrdem()){
            peca.setText("Suas peças são verdes");
            icone = casaverde;
            iconeOponente = casavermelho;
            
        }
        else{
            peca.setText("Suas peças são vermelhas");
            icone = casavermelho;
            iconeOponente = casavermelho;  
        }
        
        icone = casaverde;
            cverde1.setIcon(icone);
            cverde2.setIcon(icone);
            cverde3.setIcon(icone);
            cverde4.setIcon(icone);
        icone = casavermelho;
            cvermelho1.setIcon(icone);
            cvermelho2.setIcon(icone);
            cvermelho3.setIcon(icone);
            cvermelho4.setIcon(icone);
       espacoCartas.add(carta1);
       espacoCartas.add(carta2);
       espacoCartas.add(carta3);
       espacoCartas.add(carta4);
       espacoCartas.add(carta5);
       espacoCartas.add(carta6);
          
       casasTabuleiro.add(casa1);
       casasTabuleiro.add(casa32);
       casasTabuleiro.add(casa31);
       casasTabuleiro.add(casa30);
       casasTabuleiro.add(casa29);
       casasTabuleiro.add(casa28);
       casasTabuleiro.add(casa27);
       casasTabuleiro.add(casa26);
       casasTabuleiro.add(casa25);
       casasTabuleiro.add(casa24);
       casasTabuleiro.add(casa23);
       casasTabuleiro.add(casa22);
       casasTabuleiro.add(casa21);
       casasTabuleiro.add(casa20);
       casasTabuleiro.add(casa19);
       casasTabuleiro.add(casa18);
       casasTabuleiro.add(casa17);
       casasTabuleiro.add(casa16);
       casasTabuleiro.add(casa15);
       casasTabuleiro.add(casa14);
       casasTabuleiro.add(casa13);
       casasTabuleiro.add(casa12);
       casasTabuleiro.add(casa11);
       casasTabuleiro.add(casa10);
       casasTabuleiro.add(casa9);
       casasTabuleiro.add(casa8);
       casasTabuleiro.add(casa7);
       casasTabuleiro.add(casa6);
       casasTabuleiro.add(casa5);
       casasTabuleiro.add(casa4);
       casasTabuleiro.add(casa3);
       casasTabuleiro.add(casa2);
       casasTabuleiro.add(cverde1);
       casasTabuleiro.add(cverde2);
       casasTabuleiro.add(cverde3);
       casasTabuleiro.add(cverde4);
       casasTabuleiro.add(cvermelho1);
       casasTabuleiro.add(cvermelho2);
       casasTabuleiro.add(cvermelho3);
       casasTabuleiro.add(cvermelho4);
       casasTabuleiro.add(fverde1);
       casasTabuleiro.add(fverde2);
       casasTabuleiro.add(fverde3);
       casasTabuleiro.add(fverde4);
       casasTabuleiro.add(fvermelho1);
       casasTabuleiro.add(fvermelho2);
       casasTabuleiro.add(fvermelho3);
       casasTabuleiro.add(fvermelho4);
   
       casa1.setText("casa1");
       casa2.setText("casa2");
       casa3.setText("casa3");
       casa4.setText("casa4");
       casa5.setText("casa5");
       casa6.setText("casa6");
       casa7.setText("casa7");
       casa8.setText("casa8");
       casa9.setText("casa9");
       casa10.setText("casa10");
       casa11.setText("casa11");
       casa12.setText("casa12");
       casa13.setText("casa13");
       casa14.setText("casa14");
       casa15.setText("casa15");
       casa16.setText("casa16");
       casa17.setText("casa17");
       casa18.setText("casa18");
       casa19.setText("casa19");
       casa20.setText("casa20");
       casa21.setText("casa21");
       casa22.setText("casa22");
       casa23.setText("casa23");
       casa24.setText("casa24");
       casa25.setText("casa25");
       casa26.setText("casa26");
       casa27.setText("casa27");
       casa28.setText("casa28");
       casa29.setText("casa29");
       casa30.setText("casa30");
       casa31.setText("casa31");
       casa32.setText("casa32");
       cverde1.setText("cverde1");
       cverde2.setText("cverde2");
       cverde3.setText("cverde3");
       cverde4.setText("cverde4");
       cvermelho1.setText("cvermelho1");
       cvermelho2.setText("cvermelho2");
       cvermelho3.setText("cvermelho3");
       cvermelho4.setText("cvermelho4");
       fverde1.setText("fverde1");
       fverde2.setText("fverde2");
       fverde3.setText("fverde3");
       fverde4.setText("fverde4");
       fvermelho1.setText("fvermelho1");
       fvermelho2.setText("fvermelho2");
       fvermelho3.setText("fvermelho3");
       fvermelho4.setText("fvermelho4");

      
       
        
    }
    
    public void notificar(String mensagem){
        notificacao.setText(mensagem);
        
    }
   
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton carta1;
    private javax.swing.JButton carta2;
    private javax.swing.JButton carta3;
    private javax.swing.JButton carta4;
    private javax.swing.JButton carta5;
    private javax.swing.JButton carta6;
    private javax.swing.JButton casa1;
    private javax.swing.JButton casa10;
    private javax.swing.JButton casa11;
    private javax.swing.JButton casa12;
    private javax.swing.JButton casa13;
    private javax.swing.JButton casa14;
    private javax.swing.JButton casa15;
    private javax.swing.JButton casa16;
    private javax.swing.JButton casa17;
    private javax.swing.JButton casa18;
    private javax.swing.JButton casa19;
    private javax.swing.JButton casa2;
    private javax.swing.JButton casa20;
    private javax.swing.JButton casa21;
    private javax.swing.JButton casa22;
    private javax.swing.JButton casa23;
    private javax.swing.JButton casa24;
    private javax.swing.JButton casa25;
    private javax.swing.JButton casa26;
    private javax.swing.JButton casa27;
    private javax.swing.JButton casa28;
    private javax.swing.JButton casa29;
    private javax.swing.JButton casa3;
    private javax.swing.JButton casa30;
    private javax.swing.JButton casa31;
    private javax.swing.JButton casa32;
    private javax.swing.JButton casa4;
    private javax.swing.JButton casa5;
    private javax.swing.JButton casa6;
    private javax.swing.JButton casa7;
    private javax.swing.JButton casa8;
    private javax.swing.JButton casa9;
    private javax.swing.JButton cverde1;
    private javax.swing.JButton cverde2;
    private javax.swing.JButton cverde3;
    private javax.swing.JButton cverde4;
    private javax.swing.JButton cvermelho1;
    private javax.swing.JButton cvermelho2;
    private javax.swing.JButton cvermelho3;
    private javax.swing.JButton cvermelho4;
    private javax.swing.JLabel descarte;
    private javax.swing.JButton fverde1;
    private javax.swing.JButton fverde2;
    private javax.swing.JButton fverde3;
    private javax.swing.JButton fverde4;
    private javax.swing.JButton fvermelho1;
    private javax.swing.JButton fvermelho2;
    private javax.swing.JButton fvermelho3;
    private javax.swing.JButton fvermelho4;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel notificacao;
    private javax.swing.JLabel peca;
    private javax.swing.JLabel turno;
    // End of variables declaration//GEN-END:variables


}
